### PR TITLE
Add usage button to AMI modal overlay

### PR DESCRIPTION
**Pull request by jennysivapalan**
I think this will make it easier to find where an AMI is being used. Button links to Usage section on`/ami?imageId=[amiId]`. 

picture 59

### CODE REVIEW

**Comment by sihil** [comment]
Great idea. As Thomas says, it's unclear which AMI is being linked to. Perhaps a "- view usage" after each AMI id?

**Comment by jennysivapalan** [comment]
Ahh, I hadn't thought of that (I always assume every app is using the old AMI). Yes that makes sense, I'll make that change.

**Comment by jennysivapalan** [comment]
@thomaska @sihil Done!
picture 60

**Comment by sihil** [comment]
Looks reasonable. Despite having suggested it I'm slightly uneasy at mixing information with links that don't look like buttons. Having said that, this is a useful feature that I've wanted a few times. 👍

**Pull request merged**
